### ISSUE TITLE
General rework

### ISSUE THREAD

**Issue by Rowan-Paul** [Rowan-Paul/project-argus#24]
Rework the site for some performance improvements (basically rework #4)

- [x] Try fixing #19 
- [x] Load shows, movies, users statically (getStaticProps)
- [x] #23 Actually use typescript
- [x] pay attention to #20 
- [x] Switch to yarn
- [x] #17 add episode from different season
- [x] Add constraints to api endpoints
- [x] #22 Probably add some error handling

**Comment by Rowan-Paul** [comment]
I'm going to move all other issues to their own branch and PR this
